# Logistic Regression
- Churn Prediction using Logistic Regression

# Step 3: Import Liabraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Step 3: Load Data

In [2]:
df = pd.read_csv('churn.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

# Step 3: Data Preprocessing

In [3]:
df.shape

(7043, 21)

In [4]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Keeping important columns

In [5]:
# Define the columns to keep
columns_to_keep = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'Contract', 'TotalCharges', 'Churn']
# Select only the specified columns
df = df[columns_to_keep]

In [6]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines        Contract TotalCharges Churn  
0  No phone service  Month-to-month        29.85    No  
1                No        One year       1889.5    No  
2                No  Month-to-month       108.15   Yes  
3  No phone service        One year      1840.75    No  
4                No  Month-to-month       151.65   Yes

# Encode binary variables (e.g., Yes/No columns)

In [7]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines        Contract TotalCharges Churn  
0  No phone service  Month-to-month        29.85    No  
1                No        One year       1889.5    No  
2                No  Month-to-month       108.15   Yes  
3  No phone service        One year      1840.75    No  
4                No  Month-to-month       151.65   Yes

In [8]:
le = LabelEncoder()

Below both logics change the categorical to numerice value

In [9]:
Catagorical_col = ['gender', 'Partner', 'Dependents','PhoneService', 'MultipleLines', 'Contract', 'Churn']
for col in Catagorical_col:
    df[col] = le.fit_transform(df[col])

#     binary_col = ['Partner','Dependents', 'PhoneService' , 'Churn']
    
#     df['gender'] = df['gender'].replace({'Male':1, 'Female': 0})
#     df[binary_col] = df[binary_col].replace({'Yes':1, 'No': 0})
#    df['MultipleLines'] = df['MultipleLines'].replace({'No phone service':1, 'No': 0, 'Yes':2})
#    df['Contract'] = df['Contract'].replace({'Month-to-month':1, 'One year': 0, 'Two year': 2})    

In [10]:
df

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0   
1          1              0        0           0      34             1   
2          1              0        0           0       2             1   
3          1              0        0           0      45             0   
4          0              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7038       1              0        1           1      24             1   
7039       0              0        1           1      72             1   
7040       0              0        1           1      11             0   
7041       1              1        1           0       4             1   
7042       1              0        0           0      66             1   

      MultipleLines  Contract TotalCharges  Churn  
0                 1         0        29.85      0  
1                 0         1       1889.5      0  
2                 0         0       108.15      1  
3                 1         1      1840.75      0  
4                 0         0       151.65      1  
...             ...       ...          ...    ...  
7038              2         1       1990.5      0  
7039              2         1       7362.9      0  
7040              1         0       346.45      0  
7041              2         0        306.6      1  
7042              0         2       6844.5      0  

[7043 rows x 10 columns]

# Now data is ready for Train and Testing

# Split the dataset into training and testing sets

In [11]:
X = df.drop('Churn', axis = 1)
y = df['Churn']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [13]:
X_train['TotalCharges'] = pd.to_numeric(X_train['TotalCharges'], errors='coerce')
X_test['TotalCharges'] = pd.to_numeric(X_test['TotalCharges'], errors='coerce')

In [14]:
# Replace missing values in the 'TotalCharges' column with the mean of the column
X_train['TotalCharges'].fillna(X_train['TotalCharges'].mean(), inplace=True)
X_test['TotalCharges'].fillna(X_test['TotalCharges'].mean(), inplace=True)

C:\Users\anilk\AppData\Local\Temp\ipykernel_8724\2384259960.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['TotalCharges'].fillna(X_train['TotalCharges'].mean(), inplace=True)
C:\Users\anilk\AppData\Local\Temp\ipykernel_8724\2384259960.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always b

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5634 entries, 2142 to 860
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   gender         5634 non-null   int64  
 1   SeniorCitizen  5634 non-null   int64  
 2   Partner        5634 non-null   int64  
 3   Dependents     5634 non-null   int64  
 4   tenure         5634 non-null   int64  
 5   PhoneService   5634 non-null   int64  
 6   MultipleLines  5634 non-null   int64  
 7   Contract       5634 non-null   int64  
 8   TotalCharges   5634 non-null   float64
dtypes: float64(1), int64(8)
memory usage: 440.2 KB


# Standard Scaller

In [16]:
sc = StandardScaler()

In [17]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
X_train

array([[-1.02516569, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.42210502],
       [-1.02516569, -0.4377492 , -0.96957859, ...,  1.10833901,
         1.5775905 ,  1.25536015],
       [ 0.97545208, -0.4377492 ,  1.03137591, ...,  0.05390099,
        -0.83177379, -1.00299144],
       ...,
       [ 0.97545208, -0.4377492 ,  1.03137591, ..., -1.00053704,
        -0.83177379, -0.87799925],
       [ 0.97545208,  2.28441306, -0.96957859, ...,  1.10833901,
        -0.83177379, -0.48254445],
       [ 0.97545208, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.81110232]], shape=(5634, 9))

In [19]:
X_test

array([[-1.02516569, -0.4377492 ,  1.03137591, ...,  0.05390099,
        -0.83177379, -1.00239435],
       [ 0.97545208, -0.4377492 , -0.96957859, ...,  1.10833901,
        -0.83177379, -0.57263968],
       [-1.02516569, -0.4377492 ,  1.03137591, ..., -1.00053704,
         1.5775905 , -0.55704883],
       ...,
       [ 0.97545208, -0.4377492 ,  1.03137591, ..., -1.00053704,
         0.37290835, -0.86751688],
       [-1.02516569, -0.4377492 ,  1.03137591, ...,  0.05390099,
         1.5775905 ,  0.29587033],
       [ 0.97545208, -0.4377492 , -0.96957859, ...,  0.05390099,
        -0.83177379, -0.99949732]], shape=(1409, 9))

# Logistic Regression

In [22]:
lr = LogisticRegression()
lr_scalled = LogisticRegression()

In [24]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [25]:
y_pred

array([1, 0, 0, ..., 0, 0, 1], shape=(1409,))

# Accuracy Score

In [188]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7757274662881476

# Save model

In [189]:
import pickle

In [190]:
pickle.dump(lr,open('_06_logist_regression.pkl', 'wb'))

# Classification system

In [196]:
def prediction(gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges):
    data = {
    'gender': [gender],
    'SeniorCitizen': [SeniorCitizen],
    'Dependents': [Dependents],
    'Partner': [Partner],
    'tenure': [tenure],
    'PhoneService': [PhoneService],
    'MultipleLines': [MultipleLines],
    'Contract': [Contract],
    'TotalCharges': [TotalCharges]
    }
    # Create a DataFrame from the dictionary
    dff = pd.DataFrame(data)
    categorical_columns = ['gender', 'SeniorCitizen', 'Partner', 'Dependents','tenure', 'PhoneService', 'MultipleLines', 'Contract', 'TotalCharges']
    for column in categorical_columns:
        dff[column] = le.fit_transform(dff[column])
    dff = sc.fit_transform(dff)

    result = lr.predict(dff).reshape(1,-1)
    return result[0]

In [197]:
gender = "Female"
Seniorcitizen = "No"
Partner = "Yes"
Dependents = "No"
tenure = 1
Phoneservice="No"
multiline = "No phone service"
contact="Month-to-month"
totalcharge = 29.85

result = prediction(gender, Seniorcitizen, Partner, Dependents, tenure, Phoneservice, multiline, contact, totalcharge)

if result==1:
    print('churn')
else:
    print('not churn')

not churn


In [198]:
dff.head()

gender SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female            No     Yes         No       1           No   

      MultipleLines        Contract  TotalCharges  
0  No phone service  Month-to-month         29.85